import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Grid from '@mui/material/Grid';
import Button from '@mui/material/Button';
import Box from '@mui/material/Box';

import { KaraokeText } from '../components/KaraokeText'
import { useState } from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const listaTeste = ["porta", "porteira", "portão"]
  const [wordsList, setWordsList] = useState(listaTeste)
  const [currentWordIndex, setCurrentWordIndex] = useState(0)
 
  console.log(wordsList)

 
  return (
    <>
      <Head>
        <title>Fonokê</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Palavra Número {currentWordIndex+1}/{wordsList.length}
          </p>
          <div>
            <a
            >
              By João Soares
            </a>
          </div>
        </div>
        <div className={styles.center}>
       
        { wordsList.length === 0 ? <div>teste</div> : <KaraokeText text={wordsList[currentWordIndex]} />
          }
        </div>

        <div  className={styles.center}>
          <Grid container>
            <Grid item xs={12}>
                Palavra atual: {wordsList[currentWordIndex]}
            </Grid>
            <Grid item xs={4}>
                <Button size="large" variant='outlined'  disabled={currentWordIndex === 0} onClick={() => {setCurrentWordIndex(currentWordIndex - 1)}}>{'<'}</Button>
            </Grid>
            <Grid item xs={4}>
                <Button size="large" onClick={() => {setCurrentWordIndex(currentWordIndex)}}>Repetir</Button>
            </Grid>
            <Grid item xs={4}>
                <Button size="large" disabled={wordsList.length === currentWordIndex+1} variant='outlined' onClick={() => {setCurrentWordIndex(currentWordIndex + 1)}}>{'>'}</Button>
            </Grid>
          </Grid>
        </div>
      </main>
    </>
  )
}
